# add stages here

stages:
  data_preparation:
    cmd: python src/stage_01_data_prepare.py
    deps:
      - src/stage_01_data_prepare.py
      - src/utils
      - data/data.xml
    params:
      - config/params.yaml:
    outs:
      - artifacts/prepared_data
  
  featurization:
    cmd: python src/stage_02_featurization.py
    deps:
      - src/stage_02_featurization.py
      - src/utils
      - artifacts/prepared_data
    params:
      - config/params.yaml:
    outs:
      - artifacts/featurized_data
  
  Model_training:
    cmd: python src/stage_03_training.py
    deps:
      - src/stage_03_training.py
      - src/utils
      - artifacts/featurized_data
    params:
      - config/params.yaml:
    outs:
      - artifacts/models

  Model_eval:
    cmd: python src/stage_04_model_evalution.py
    deps:
      - src/stage_04_model_evalution.py
      - src/utils
      - artifacts/models
    params:
      - config/params.yaml:
    metrics:
      - metrics_scores/scores.json:
          cache: false
    plots:
      - plot/prc.json:
          cache: false
          x: precision
          y: recall
      - plot/roc.json:
          cache: false
          x: fpr
          y: tpr

    # outs:
    #   - metrics_scores/
    #   - plot/