Logger: 
      log_file_name: logs
      log_location: Log

Data:
    source_dir: data
    data_file: data.xml

Artifact:
    artifact_dir: artifacts
    prepared_data_dir: prepared_data
    train_data: train.tsv
    test_data: test.tsv
    Featurized_Data_Dir: featurized_data
    Featurized_Train_Data: featurized_train.tsv
    Featurized_Test_Data: featurized_test.tsv
    Train_Tfidf_matrix: train_words_tfidf_matrix.pkl
    Test_Tfidf_matrix: test_words_tfidf_matrix.pkl
    Model_dir: models
    model_name: randomForestClassifier

Plots:
    plot_dir: plot
    PRC:  prc.json
    ROC:  roc.json

Metrics:
    scores: scores.json
    path: metrics_scores

    
