Prepare:
  split: 0.3
  seed: 101
  tag: <python>
  column_names: "pid\tlabel\ttext\n"
featurization:
  max_features: 3200
  ngram_range: 3
Training:
  seed: 42
  n_est: 1500
  n_jobs: -1
  min_split: 8
  verbose: 4

