Prepare:    
      split: 0.3
      seed: 42
      tag: <python>
      column_names: "pid\tlabel\ttext\n"
      
featurization:
      max_features: 3000
      ngram_range: 4
Training:
      seed: 42
      n_est: 1000
      n_jobs: -1
      min_split: 16
      verbose: 4

